---
id: satomi
base_name: kanatan
tags:
- rabbit
- shogi
presentation_date: 2013/06/xx
version: 2013.6.0.0
licenses:
- CC BY-NC-ND 3.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :rd
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
